feat(cicd): add style for coding style errors

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -18,3 +18,11 @@ jobs:
       - name: run coding style checker
         run : |
           ./scripts/go_coding_style_checker.sh
+          if [ -s ./scripts/gofmt_output.txt ]; then
+            cat ./scripts/gofmt_output.txt | while read line; do
+              echo "::error file=$line::"
+            done
+            exit 1
+          else
+            exit 0
+          fi
